// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQHXaChkassWKi629Lht4cyQ7VkguPyJA',
    appId: '1:138524547044:web:e8e0e58a6c55844ffbd9f1',
    messagingSenderId: '138524547044',
    projectId: 'colourwalk-4f81e',
    authDomain: 'colourwalk-4f81e.firebaseapp.com',
    storageBucket: 'colourwalk-4f81e.firebasestorage.app',
    measurementId: 'G-M734SWZZKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAot4u7y8Ymj0IoEpRLQltVTbBA-q6JXVw',
    appId: '1:138524547044:android:3f8e83dc077ab558fbd9f1',
    messagingSenderId: '138524547044',
    projectId: 'colourwalk-4f81e',
    storageBucket: 'colourwalk-4f81e.firebasestorage.app',
  );
}
